name: Compile Custom Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu make bc libssl-dev \
            libelf-dev bison flex python3 zip unzip \
            wget curl lld llvm libncurses5 libncurses-dev

            
      - name: Download Google Clang (r383902)
        run: |
          echo "Downloading exact Clang version required by Makefile..."
          mkdir -p toolchain/clang/host/linux-x86/clang-r383902
          wget -O clang.tar.gz "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-11.0.0_r48/clang-r383902.tar.gz"
          tar -C toolchain/clang/host/linux-x86/clang-r383902/ -xzf clang.tar.gz
          rm clang.tar.gz

      - name: Download AOSP GCC (4.9)
        run: |
          echo "Downloading AOSP GCC 4.9 required by Makefile..."
          mkdir -p toolchain/gcc/linux-x86/aarch64
          git clone --depth 1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

      - name: Patch Defconfig & Fix Broken Paths
        run: |
          echo "Injecting Droidspaces support into the defconfig..."
          CONFIG_FILE="arch/arm64/configs/exynos850-a13xx_defconfig"
          echo "CONFIG_IPC_NS=y" >> $CONFIG_FILE
          echo "CONFIG_BRIDGE=y" >> $CONFIG_FILE
          echo "CONFIG_STP=y" >> $CONFIG_FILE
          echo "CONFIG_USER_NS=y" >> $CONFIG_FILE
          echo "CONFIG_NAMESPACES=y" >> $CONFIG_FILE
          
          echo "Fixing Samsung's missing Himax directory..."
          mkdir -p drivers/input/touchscreen/himax/himax_83xxx_i2c
          touch drivers/input/touchscreen/himax/himax_83xxx_i2c/Makefile
          

      - name: Build Kernel
        run: |
          # Set architecture to 64-bit as required by your setup
          export ARCH=arm64
          
          echo "Cleaning workspace..."
          
          echo "Applying exynos850-a13xx_defconfig..."
          make O=out exynos850-a13xx_defconfig
          
          echo "Starting compilation on all CPU cores..."
          make -j$(nproc --all) O=out

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Kernel-Image
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/dts/exynos/*.dtb
          compression-level: 9
          
